[build]
  command = "hugo --minify --baseURL https://blog.svenpeter.dev/"

[context.production]
  environment = { HUGO_VERSION = "0.82.1" }

[[redirects]]
  from = "/js/plausible.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, s-maxage=604800, max-age=604800"
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, s-maxage=604800, max-age=604800"
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, s-maxage=604800, max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-maxage=604800, max-age=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-maxage=604800, max-age=604800"
